name: goinshape
description: Simple responsive calorie counter
publish_to: "none"

environment:
 sdk: ">=3.3.0 <4.0.0"

dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^1.0.8

 # storage / db
 shared_preferences: ^2.2.3
 sqflite: ^2.3.3
 sqflite_common_ffi: ^2.3.3
 path: ^1.9.0
 sembast: ^3.7.1
 sembast_web: ^2.3.0

dev_dependencies:
 flutter_lints: ^4.0.0
 flutter_test:
  sdk: flutter

flutter:
 uses-material-design: true
